name: HyperBian release

on:
  push:
    branches:
      - master

#  repository_dispatch:
#    types: [hyperion_push]

jobs:
  rpi-image:
    name: "Build HyperBian image"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      # install dependencies
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y coreutils quilt parted qemu-user-static debootstrap zerofree zip dosfstools bsdtar libcap2-bin grep rsync xz-utils file git curl bc

      # build image
      - name: Build HyperBian
        run: |
          git clone https://github.com/RPi-Distro/pi-gen.git
          touch ./pi-gen/stage3/SKIP ./pi-gen/stage4/SKIP ./pi-gen/stage4/SKIP_IMAGES
          touch ./pi-gen/stage5/SKIP ./pi-gen/stage5/SKIP_IMAGES
          cp -R stage-hyperbian pi-gen/stage-hyperbian
          cp config pi-gen/config && cd pi-gen
          sudo ./build.sh
          mv ./deploy/*.img ./deploy/HyperBian.img

      # create release and upload image
      - name: Create release and upload image
        uses: softprops/action-gh-release@v1
        with:
          name: HyperBian
          tag_name: HyperBian
          files: "pi-gen/deploy/HyperBian.img"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

